name: entity_repository
description: A package to annotate abstract classes with entityModel and it generates the references and lookups. It uses hive under the hood
version: 0.2.0
homepage: https://mbaun.dev
repository: https://github.com/Manuelbaun/entity_repository

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  hive: ^1.4.4+1
  meta: ^1.2.4

dev_dependencies:
  # analyzer: ">=0.39.12 <0.40.0"
  analyzer: ^0.40.6
  pedantic: ^1.9.2
  test: ^1.15.6
  build_runner: ^1.10.3