name: entity_repository
description: A package to annotate abstract classes with entityModel and it generates the references and lookups. It uses hive under the hood
version: 0.1.6
homepage: https://mbaun.dev
repository: https://github.com/Manuelbaun/entity_repository

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  hive: ^1.4.4+1
  meta: ^1.2.3
  analyzer: ">=0.39.12 <0.40.0"
  build: ^1.3.0
  source_gen: ^0.9.6
  msgpack_dart: ^0.0.7

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.4
  build_runner:
