# Read about `build.yaml` at https://pub.dev/packages/build_config
builders:
  property_entity_repo:
    import: "package:entity_repository_generator/builder.dart"
    builder_factories: ["entityRepositoryGenerator"]
    build_extensions: { ".dart": [".g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]

  entity_database_generator:
    import: "package:entity_repository_generator/builder.dart"
    builder_factories: ["entityDatabaseGenerator"]
    build_extensions: { ".dart": [".db.dart"] }
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
