name: entity_repository_example
description: The example repo for the entity_repository package
version: 0.1.0
author: Manuel Baun <manuel.baun@gmail.com>

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  entity_repository: ^0.2.0
  msgpack_dart: ^0.0.7

dev_dependencies:
  build_runner: ^1.10.6
  entity_repository_generator: ^0.1.6

dependency_overrides:
  entity_repository:
    path: ..\entity_repository

  entity_repository_generator:
    path: ..\entity_repository_generator
